language: go

go:
  - 1.8
  - 1.9

before_script:
after_script:
script:


jobs:
 include:
  - stage: test
    script: go test -v ./abbrvs/...
    script: go test -v ./service/...
  - stage: benchmarks
    script: go test -run=xXX -bench . ./services/...
  - stage: deploy
    script: echo "do nothing... :)"

