language: go

go:
  - 1.8
  - 1.9

before_install:
after_install:
before_script:
after_script:
script:


jobs:
 include:
  - stage: coverage
    script: go test -cover ./internal/...
    script: go test -cover ./service/...
  - stage: test
    script: go test -v ./internal/...
    script: go test -v ./service/...
  - stage: benchmarks
    script: go test -run=xXX -bench=. ./service/...
  - stage: deploy
    script: echo "do nothing... :)"

