# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/influx6/wordies
    steps:
      - checkout
      - run: go test -run=xXX -cover ./internal/...
      - run: go test -run=xXX -cover ./service/...
      - run: go test -v ./internal/...
      - run: go test -v ./service/...
      - run: go test -bench=. -run=xXX ./service/...
      - run: go test -run=xXX -bench=.
